In [43]:
import pandas as pd
import numpy as np

df = pd.read_csv("ft_eng_data.csv")

In [44]:
df.head()

,Unnamed: 0,customer_id,name,signup_date,annual_income,monthly_spend,city,plan
0,0,1001,Dev Santos,2023-04-25,23500.0,11.36,Lagos,basic
1,1,1002,Jonas Dubois,2024-02-04,26300.0,13.83,Lima,plus
2,2,1003,Noor Reyes,2024-06-25,520500.0,26.50,Berlin,premium
3,3,1004,Dev Oyelaran,2023-12-25,288500.0,27.88,Lagos,basic
4,4,1005,Kwame Okafor,2024-08-24,39300.0,14.21,Lima,basic

In [45]:
# AS_OF = pd.Timestamp("2025-01-01")
df = df.drop("Unnamed: 0", axis=1)
df.head()

,customer_id,name,signup_date,annual_income,monthly_spend,city,plan
0,1001,Dev Santos,2023-04-25,23500.0,11.36,Lagos,basic
1,1002,Jonas Dubois,2024-02-04,26300.0,13.83,Lima,plus
2,1003,Noor Reyes,2024-06-25,520500.0,26.50,Berlin,premium
3,1004,Dev Oyelaran,2023-12-25,288500.0,27.88,Lagos,basic
4,1005,Kwame Okafor,2024-08-24,39300.0,14.21,Lima,basic

In [46]:
missing = df.isna().sum()
print(missing)

customer_id       0
name              0
signup_date       5
annual_income    22
monthly_spend     0
city              0
plan              0
dtype: int64

In [48]:
df["signup_date"] = pd.to_datetime(df["signup_date"], format="%Y-%m-%d", errors="coerce")

In [49]:
df.head()

,customer_id,name,signup_date,annual_income,monthly_spend,city,plan
0,1001,Dev Santos,2023-04-25,23500.0,11.36,Lagos,basic
1,1002,Jonas Dubois,2024-02-04,26300.0,13.83,Lima,plus
2,1003,Noor Reyes,2024-06-25,520500.0,26.50,Berlin,premium
3,1004,Dev Oyelaran,2023-12-25,288500.0,27.88,Lagos,basic
4,1005,Kwame Okafor,2024-08-24,39300.0,14.21,Lima,basic

In [51]:
df["tenure_days"]
df["tenure_months"]
df["signup_month"] = df["signup_date"].dt.month
df["signup_year"] = df["signup_date"].dt.year
df["signup_day"] = df["signup_date"].dt.day
df["is_weekend"]
df["dow"] = = df["signup_date"].dt.

KeyError: 'tenure_days'