# PANDAS AND NUMPY

* NUMPUY

In [1]:
import pandas as pd
import numpy as np

In [5]:
list1 = [1,2,3]
list2 = [4,5,6]

In [6]:
list3= list1 + list2
list3

[1, 2, 3, 4, 5, 6]

In [7]:
list1*2

[1, 2, 3, 1, 2, 3]

In [8]:
list1**(0.5)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'float'

In [9]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])

In [10]:
array_3 = array_1+array_2
array_3

array([5, 7, 9])

In [11]:
array_3**(0.5)

array([2.23606798, 2.64575131, 3.        ])

In [12]:
array_3*2

array([10, 14, 18])

In [15]:
mat_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
mat_2 = np.array([[0,2,1],[-4,3,6],[11,-8,9]])
mat_2

array([[ 0,  2,  1],
       [-4,  3,  6],
       [11, -8,  9]])

In [17]:
mat_1 * mat_2

array([[  0,   4,   3],
       [-16,  15,  36],
       [ 77, -64,  81]])

In [18]:
mat_1 + mat_2

array([[ 1,  4,  4],
       [ 0,  8, 12],
       [18,  0, 18]])

In [21]:
np.linalg.det(mat_1)

np.float64(-9.51619735392994e-16)

* PANDAS

In [22]:
import random

In [35]:
# Creating Pandas DataFrame
df1 =  pd.DataFrame(np.random.randn(10,5))

In [36]:
df1

          0         1         2         3         4
0  0.427241 -0.259550  0.157549 -0.989852  0.274097
1 -0.346453  0.298021  0.430820 -1.050021  0.994937
2  1.018123  0.493739  0.389043  0.479966  1.177549
3 -0.065732  1.194226  1.277270 -0.562615 -0.223165
4 -0.632695 -0.870943 -1.373360  0.587516 -0.004670
5 -0.735568 -0.184938 -0.459622 -1.681869 -0.099237
6 -1.859542 -0.211122  0.953620 -0.971193  1.429742
7 -0.324398  1.059255  0.020937 -1.574682  0.009265
8  0.419122  0.385822  0.072350  0.673641 -0.172629
9  0.852065 -0.057564  1.731864  0.937286 -1.006777

In [37]:
df1.rename(columns = {0:"Column1", 
                      1:"Column2",
                      2:"Column3",
                      3:"Column4",
                     4:"Column5"})

    Column1   Column2   Column3   Column4   Column5
0  0.427241 -0.259550  0.157549 -0.989852  0.274097
1 -0.346453  0.298021  0.430820 -1.050021  0.994937
2  1.018123  0.493739  0.389043  0.479966  1.177549
3 -0.065732  1.194226  1.277270 -0.562615 -0.223165
4 -0.632695 -0.870943 -1.373360  0.587516 -0.004670
5 -0.735568 -0.184938 -0.459622 -1.681869 -0.099237
6 -1.859542 -0.211122  0.953620 -0.971193  1.429742
7 -0.324398  1.059255  0.020937 -1.574682  0.009265
8  0.419122  0.385822  0.072350  0.673641 -0.172629
9  0.852065 -0.057564  1.731864  0.937286 -1.006777